# SPDX-License-Identifier: Apache-2.0
#!BuildTag: elemental/charts/elemental-lifecycle-manager:0.1.0

apiVersion: v2
name: elemental-lifecycle-manager
description: A Helm chart for the Elemental Lifecycle Manager
type: application
version: 0.1.0
appVersion: "0.1.0"
